notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: aEE3FILmPONrxBuo67BMy/TJaBaHCvdf52RrK3UiNI9hpTZhPZBAXen2WX/4zMST8yoaVmI2n394Mb/hP2aQ+biFLHF+6135Pf6AvVObYWkSzp0y4XDWDL4TJgvAggNFxPp6n80d1IAzbw5xsM+n/DKn2JnDRaxCPhT5mz39qh1X/ZGn4FKmiObRZSQFYqP84HWYuKBxzrOVAIm6ZLi9OFpvXlMPo8ezLQGDle0S5DMO8P6pDlPEXelG1Wil5xy5cQzW3Vf4OBxpZSEatgOdASXR0GtBveGVUpFcqc7KS3BncsQGr+SqtlIRPYgBHdlwBTfYtXhK0Q8s1GIms3eGd+iy4JzTO/MqXh9E6ONjp/gYSiFP/2/ixZJwykfgSWBH3xyZGjpMZE9O/SxGEYj0aCmBxeKgXM0iqA/QUq73LE4MlOQS/UUtteSJ0nTP1kzyHHXrxU5CBab9ZPM4ZJuTYev7CH1s2l1fuCt1OUQ2OmuPZ1QbFuYMYmAaCP0njH/uZiC3mjKIMzrept89B1eyFRthWgmjPbtdvdMpEbXigqjAGlQnyGx1lV8jxQre0+4jfSy10+KZNqpv2+oNT1bogHuZv+cODEvTh1ClbVk2r8oKZQIcabDfrn+Islq8rTJTdEacbxNgsBhJiKryhonXSIEFpIDuX/4VmrABBoSJ2NQ=
env:
  global:
  - secure: PvNYLMxMuL58vjhs9M8YiVK4nI5YyUX+Qamz0r0pf3MDbZcLEejxlyCPPcNpd5BlEKdGP/FQcCeWRsJqSu30PGHBb0YCdYsjuMr/oK1NhGOg/2FXbRRnGN3/9+/Eg4akVage/TIkIigS1v6numtbWCcFtOU51cRoWuG+xnBN1lT96baN0VX6rhExbeFzbGAUskMj2veCboLy31xI1ohv1Mx0wJV7n20TRYlLfKK0jpatlgA+oDXQOnye0GiZ+fvoZiZ6GEoB65bFbfdGYrTPMNxnjhxhGkYEtCgeYRLuEuBiQXvzWiyzSdnCvM1DvUdBgRqmBkEHtNf+PJ0vNrJXEKvD2DjPZCHzhcjBQu272OaLJls7NjfmhiMluA6zqXZ8G/v041Zc+OMGAN3ThfkzAEXux+0eDPuHkK3TDzaGwVBJV5Fv61x/noGkZxu/cX/DbZT6uv8z1I9ZFFe7I4+2b8vvtBTCDpR18u/GWdRspooer9QOyPvaemMRGQxFK3uw7YFX7yEm6qDC2ekZmzjfBBB6qXomA9UlfoQGNiHoaPFHx4jPdeOaUSE+kX5u1FcjNOENmkZhLIiWZLGu3LEl46AY+E9oDxqLi2R/bLAlCLlMG021RLWrVzct75H1oqI15gHnwRo8dfuZnfSvhJz8/M4pKcyrK7c5rWRgFR4kgx0=
matrix:
  fast_finish: true
  include:
  - name: Tests
    language: node_js
    node_js: '10'
    cache:
      yarn: true
      directories:
      - "~/.cache"
      - ".eslintcache"
    script:
    - yarn check-all
    - yarn build
    after_success:
    - travis_wait yarn ndla-scripts now-travis
  - name: Release
    language: python
    if: branch = master AND type = push
    python: 3.7
    dist: bionic
    services:
    - docker
    cache: pip
    before_install:
    - pip install awscli
    - "$(aws ecr get-login --no-include-email --region eu-west-1)"
    - git clone --depth 1 https://knowit-at-ndla:$TRAVIS_RELEASE_GITHUB_TOKEN@github.com/ndlano/deploy.git
      ../deploy
    - export NDLA_HOME=$(realpath $(pwd)/../)
    - export NDLA_DEPLOY=$NDLA_HOME/deploy
    - export DEPLOY_VERSION=$(git -C $NDLA_DEPLOY rev-parse --short=7 HEAD)
    - export DEPLOY_DOCKER_REPO=784120951859.dkr.ecr.eu-west-1.amazonaws.com/ndla/deploy
    - docker pull $DEPLOY_DOCKER_REPO:$DEPLOY_VERSION || true
    install:
    - eval "$($NDLA_DEPLOY/scripts/bin/ndla init -)"
    env:
    - SSH_AUTH_SOCK=/tmp/mock_sock
    script:
    - ndla release listing-frontend --update-chart
    before_cache:
    - docker push $DEPLOY_DOCKER_REPO:$DEPLOY_VERSION
  allow_failures:
  - name: Release
